AppBundle\Entity\RefreshToken:
    type: entity
    table: refresh_token
    id:
        id:
            id: true
            type: integer
            generator: { strategy: AUTO }
    manyToOne:
        customer:
            targetEntity: Customer
            joinColumn:
                name: id
                referencedColumnName: id
        client:
            targetEntity: Client
            joinColumn:
                name: id
                referencedColumnName: id
    lifecycleCallbacks: {  }
