apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-app
  labels:
    name: k8s-app
spec:
  replicas: 1
  selector:
    name: k8s-app
  template:
    metadata:
      labels:
        name: k8s-app
    spec:
      containers:
        - name: k8s-app
          image: k8s_php_dev
          ports:
            - containerPort: 80
            - containerPort: 8080
          volumeMounts:
            - mountPath: /var/www
              name: www-data
              readOnly: false
      volumes:
        - name: www-data
          hostPath:
            path: /home/bitgandtter/Documents/development/php/k8s_devel_env